name: 🐛 Bug
description: Report a bug (Outside contributors only).
labels: [⚕️NEEDS TRIAGE]
type: "Bug"
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I searched whether or not an issue already exists for the bug I encountered.
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps taken to reproduce the issue.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    multiple: true
    options:
    - Windows
    - Linux
    - Android
    - Mac OS
    - iOS
    - Other
  validations:
    required: true

- type: textarea
  attributes:
    label: OS Versions
    description: If you know what version of each operating system the bug occurrs on, enter it here.
    placeholder: |
      Windows:
        1. Open the start menu.
        2. Type `winver` and press enter.
      MacOS:
        1. Click the Apple icon in the top left corner.
        2. Click `About This Mac`.
      Linux:
        1. Open a terminal.
        2. Type `cat /etc/os-release` and press enter.
  validations:
    required: false

- type: textarea
  attributes:
    label: Application/Library Version
    description: Enter the version of the application/library that the bug occurred on.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything Else
    description: Links? References? Please provide anything that will give us more context about the issue you encountered. 
    placeholder: "Tip: You can drag and drop files here (i.e. images, log files etc.)." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] I have fixed the bug, and everything works as expected.
      - [ ] I have manually tested the changes to confirm that no bugs or behavior changes were introduced.
      - [ ] All the unit tests have been executed and passed locally after PR work is complete.
  validations:
    required: true
    render: markdown

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
