name: 🐛 Bug
description: File a bug (Outside contributors only).
title: "🐛"
labels: [bug, ⚕️NEEDS TRIAGE]
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I have updated the title without removing the 🐛 emoji.
      required: true
    - label: I searched whether or not an issue already exists for the bug I encountered.
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps taken to reproduce the issue.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    multiple: true
    options:
    - Windows
    - Linux
    - Android
    - Mac OS
    - iOS
    - Other
  validations:
    required: true

- type: textarea
  attributes:
    label: OS Version
    description: If you know what OS version the bug occurred on, enter it here.
    placeholder: v1.2.3
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything Else
    description: Links? References? Please provide anything that will give us more context about the issue you encountered. 
    placeholder: "Tip: You can drag and drop files here (i.e. images, log files etc.)." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete in order to satisfy the Definition of Done.
    value: |
      ```[tasklist]
      ### The items to complete in order to satisfy the Definition of Done.
      - [ ] I have fixed the bug, and everything now works as expected.
      - [ ] I have manually tested the changes to confirm that no bugs or behavior changes were introduced.
      - [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      - If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

      💡Warning💡
      If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
      Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
      </details>

      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type              | Label                     |
      |:-------------------------|:--------------------------|
      | Bug Fixes                | `🐛bug`                   |
      | Breaking Changes         | `🧨breaking changes`      |
      | New Feature              | `✨new feature`           |
      | CICD Changes             | `♻️cicd`                  |
      | Config Changes           | `⚙️config`                |
      | Performance Improvements | `🏎️performance`           |
      | Code Doc Changes         | `🗒️documentation/code`    |
      | Product Doc Changes      | `📝documentation/product` |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label             |
      |:--------------------|:------------------|
      | Low Priority        | `low priority`    |
      | Medium Priority     | `medium priority` |
      | High Priority       | `high priority`   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
