name: 🐛 Bug
description: File a bug.
title: "🐛"
labels: [bug, ⚕️NEEDS TRIAGE]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I have updated the title without removing the 🐛 emoji.
      required: true
    - label: I searched whether or not an issue already exists for the bug I encountered.
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps taken to reproduce the issue.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
