name: ✨ Enhancement
description: Software improvement. (Not a feature)
projects: ["KinsonDigital/11"]
type: "Enhancement"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > The title should be short and descriptive.

- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: A priority label has been added to this issue.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the enhancement.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown
