name: 🔥 HotFix
description: Create a hotfix release issue for a project (Project maintainers only).
title: "🔥"
labels: [bug, 🔥Hot Fix Release🚀]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I have updated the title without removing the 🐛 emoji.
      required: true
    - label: I searched whether or not an issue already exists for the bug I encountered.
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps taken to reproduce the issue.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    options:
    - label: Windows
    - label: Linux
    - label: Android
    - label: Mac OS
    - label: iOS
    - label: Other
  validations:
    required: true

- type: textarea
  attributes:
    label: OS Version
    description: If you know what OS version the bug occurred on, enter it here.
    placeholder: v1.2.3
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything Else
    description: Links? References? Please provide anything that will give us more context about the issue you encountered. 
    placeholder: "Tip: You can drag and drop files here (i.e. images, log files etc.)." 
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Perform Release ToDo List
    description: Complete the following items to perform a release.
    options:
    - label: Add `🔥Hot Fix Release🚀` label to this issue.  
    - label: Issue is assigned to a project.
    - label: Issue is assigned to a milestone.
    - label: Release PR linked to this issue.
    - label: All unit tests have been executed locally and have passed. _(Check out the appropriate release branch before running tests)_.
    - label: Version in project file updated _(All changes made directly on the release branch (master))_.
    - label: Release notes created and added _(All changes made directly on the release branch (master))_.
    - label: Manual QA Testing completed _(if applicable)_.
    - label: Pull request has been approved and merged into a release branch before performing the release. _(Releases are performed on the master branch)_.
    - label: Release to **_production_** complete. _(The release is performed by running the `🚀Production Release` workflow)_.


# POST-RELEASE TODO LIST
- type: checkboxes
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    options:
    - label: The GitHub release has been created and is correct. 
    - label: The NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/) _(if applicable)_.
    - label: Announcement of release on [Twitter](https://twitter.com/KDCoder) verified _(if applicable)_. _(Announcement should be performed automatically with the release)_.
    - label: Announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel _(if applicable)_.

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>HotFix Purpose</summary>_**

      The purpose of a hotfix is to release a fix to something wrong to production as soon as possible.
      This concept should be treated very carefully.  This should only happen if the software is simply broken and
      _**UNUSABLE**_.  If there is a simple workaround or the issue is minor, then a hotfix should not be required.

      A hotfix should be a rare occasion and if it has been occurring often, then the development and release process
      should be reviewed for improvements to try and help prevent a hotfix from occurring.
      </details>

      ---

      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      </details>

      ---

      **_<details closed><summary>Version Updating</summary>_**
      
      The version can be updated by setting the values of the `<Version/>` and `<FileVersion/>` XML tags in the project file.
      The `<Version/>` and `<FileVersion/>` values can hold production and preview releases.
      The `<AssemblyVersion/>` XML tag can only hold production values.  Preview values are not aloud.

      NOTE: This is a hotfix so a preview release version is not aloud.

      ``` xml
      <!--Production Release Example-->
      <Version>1.2.3</Version>
      <FileVersion>1.2.3</FileVersion>
      <AssemblyVersion>1.2.3</AssemblyVersion>
      ```
      </details>

      ---

      **_<details closed><summary>Release Notes</summary>_**

      By default, the release notes go into a **_ReleaseNotes_** folder inside of the **_Documentation_** folder with the **_Documentation_** folder at the root of the repository.
      Production release notes path: **_./Documentation/ReleaseNotes/ProductionReleases_**.

      Release note file names must follow a particular syntax and are in markdown format so they can be added to the release.

      #### Release Notes File Name Syntax:
      - **Production Release Notes:**
        - **Syntax:** Release-Notes-v#.#.#.md
        - **Example:** Release-Notes-v1.2.3.md

      Changes such as release notes and version updates should be committed to the destination branch (master) in the pull request attached to this issue.
      </details>

      ---
  validations:
    required: true
    render: markdown


# CODE OF CONDUCT
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true