name: 🚀 Preview Release To Do List
description: Used to perform a release (Project maintainers only).
title: "🚀Preview Release"
body:
- type: textarea
  attributes:
    label: Issues Released
    placeholder: |
      Create a list of all the items being released.
      Example:
      - #10
      - #20
    description: The list of issues that will be released.
  validations:
    required: true
    render: markdown


- type: checkboxes
  attributes:
    label: Perform Release ToDo List
    description: Complete the following items to perform a release.
    options:
    - label: Release PR linked to this issue.
    - label: Add `🚀Preview Release` label to this issue. 
    - label: All issues listed in the **_Issues Released_** section above.
    - label: All issues in the _**Issues Released**_ section are closed and all issue tasks are complete.
    - label: All unit tests have been executed locally and have passed. _(Check out the appropriate release branch before running tests)_.
    - label: Version in project file updated _(All changes made directly on the release branch)_.
    - label: Release notes created and added _(All changes made directly on the release branch)_.
    - label: Manual QA Testing completed _(if applicable)_.
    - label: Pull request has been approved and merged into a release branch before performing the release. _(Releases are performed on preview branches)_.
    - label: Release to **_preview_** complete. _(The release is performed by running the `🚀Preview Release` workflow)_.


# POST-RELEASE TODO LIST
- type: checkboxes
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    options:
    - label: The GitHub release has been created and is correct. 
    - label: If applicable, the NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/).
    - label: Announcement of release on [Twitter](https://twitter.com/KDCoder) verified _(if applicable)_. _(Announcement should be performed automatically with the release)_.
    - label: Announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel.

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      </details>

      ---

      **_<details closed><summary>Version Updating</summary>_**
      
      The version can be updated by setting the values of the `<Version/>` and `<FileVersion/>` XML tags in the project file.

      ``` xml
      <!--Syntax for preview releases-->
      <Version>1.2.3-preview.4</Version>
      <FileVersion>1.2.3-preview.4</FileVersion>

      ```
      </details>

      ---

      **_<details closed><summary>Release Notes</summary>_**

      The release notes go into the appropriate folder:
      - **Preview Release Notes** go into the **_~/Documentation/ReleaseNotes/PreviewReleases_** folder.

      Release note file names must follow a particular syntax and are in markdown format so they can be added to the release.

      #### Release Notes File Name Syntax:
      - **Preview Release Notes:**
        - **Syntax:** Release-Notes-v\<_major_\>.\<_minor_\>.\<_patch_\>-preview.\<_prev-num_\>.md
        - **Example:** Release-Notes-v1.0.0-preview.4.md

      Changes such as release notes and version updates should be committed to the same source branch in the pull request attached to this issue.
      </details>

      ---
  validations:
    required: true
    render: markdown


# CODE OF CONDUCT
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
