name: 🚀 Preview Release To Do List
description: Used to perform a release (Project maintainers only).
title: "🚀Preview Release"
labels: [🚀Preview Release]
projects: ["KinsonDigital/11"]
body:

- type: textarea
  attributes:
    label: Pre-Release ToDo List
    description: Complete the following items to perform a release.
    value: |
      ```[tasklist]
      - [ ] All of the issues in the assigned milestone are closed and all issue tasks are complete.
      - [ ] The `🚀Preview Release` label has been added to this issue.
      - [ ] This issue is assigned to a project.
      - [ ] This issue is assigned to a milestone.
      - [ ] The release pull request is linked to this issue.
      - [ ] All of the unit tests have been executed locally and have passed. _(Check out the appropriate branch before running tests)_.
      - [ ] The version has been updated. _(All changes made directly on a 'prev-release' branch)_.
      - [ ] The release notes have been created and added. _(All changes made directly on a 'prev-release' branch)_.
      - [ ] All manual QA Testing completed. _(if applicable)_
      - [ ] The pull request has been approved and merged into the _**preview**_ branch before performing the release. _(Releases are performed on the preview branch)_.
      - [ ] The preview release has been completed. _(The release is performed by running the `🚀Release` workflow)_.
      ```
  validations:
    required: true
    render: markdown

# POST-RELEASE TODO LIST
- type: textarea
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    value: |
      ```[tasklist]
      - [ ] The GitHub release has been created and is correct. 
      - [ ] The NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/). _(if applicable)_
      - [ ] An announcement of the release on [X](https://x.com/KDCoder) has been verified. _(if applicable)_
      - [ ] An announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel. _(if applicable)_
      - [ ] The documentation is website released with updated or added tutorials. _(if applicable)_
      - [ ] The documentation is website released with updated API changes. _(if applicable)_
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      </details>

      ---

      **_<details closed><summary>Version Updating</summary>_**
      
      The version can be updated by setting the values of the `<Version/>` and `<FileVersion/>` XML tags in the project file.
      The `<Version/>` and `<FileVersion/>` values can hold production and preview releases.
      The `<AssemblyVersion/>` XML tag can only hold production values.  Preview values are not allowed.

      ``` xml
      <!--Preview Release Example-->
      <Version>1.2.3-preview.4</Version>
      <FileVersion>1.2.3-preview.4</FileVersion>
      <AssemblyVersion>1.2.3</AssemblyVersion>
      ```

      Version changes should be committed to a _**prev-release**_ head branch for the the pull request linked to this issue.
      </details>

      ---

      **_<details closed><summary>Release Notes</summary>_**

      Release notes are created automatically when running the _**🚁Prepare Release**_ workflow.  The release notes
      should be reviewed and changed appropriately.

      Release note file names must follow a particular syntax and are in markdown format so they can be added to the release.

      #### Release Notes File Name Syntax:
      - **Preview Release Notes:**
        - **Syntax:** Release-Notes-v#.#.#-preview.#.md
        - **Example:** Release-Notes-v1.2.3-preview.4.md

      Release note changes should be committed to a _**prev-release**_ head branch for the the pull request linked to this issue.
      </details>

      ---
  validations:
    required: true
    render: markdown


# CODE OF CONDUCT
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/CODE_OF_CONDUCT.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
