name: 🚀 Production Release To Do List
description: Used to perform a release (Project maintainers only).
title: "🚀Production Release"
body:

- type: checkboxes
  attributes:
    label: Pre-Release ToDo List
    description: Complete the following items to perform a release.
    options:
    - label: All issues in the assigned milestone are closed and all issue tasks are complete.
    - label: Add `🚀Production Release` label to this issue.  
    - label: Issue is assigned to a project.
    - label: Issue is assigned to a milestone.
    - label: Release PR linked to this issue.
    - label: All unit tests have been executed locally and have passed. _(Check out the appropriate release branch before running tests)_.
    - label: Version in project file updated _(All changes made directly on the release branch (master))_.
    - label: Release notes created and added _(All changes made directly on the release branch (master))_.
    - label: Manual QA Testing completed _(if applicable)_.
    - label: Pull request has been approved and merged into a release branch before performing the release. _(Releases are performed on the master branch)_.
    - label: Release to **_production_** complete. _(The release is performed by running the `🚀Production Release` workflow)_.


# POST-RELEASE TODO LIST
- type: checkboxes
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    options:
    - label: The GitHub release has been created and is correct. 
    - label: The NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/) _(if applicable)_.
    - label: Announcement of release on [Twitter](https://twitter.com/KDCoder) verified _(if applicable)_. _(Announcement should be performed automatically with the release)_.
    - label: Announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel _(if applicable)_.

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      </details>

      ---

      **_<details closed><summary>Version Updating</summary>_**
      
      The version can be updated by setting the values of the `<Version/>` and `<FileVersion/>` XML tags in the project file.
      The `<Version/>` and `<FileVersion/>` values can hold production and preview releases.
      The `<AssemblyVersion/>` XML tag can only hold production values.  Preview values are not allowed.

      ``` xml
      <!--Production Release Example-->
      <Version>1.2.3</Version>
      <FileVersion>1.2.3</FileVersion>
      <AssemblyVersion>1.2.3</AssemblyVersion>
      ```
      </details>

      ---

      **_<details closed><summary>Release Notes</summary>_**

      By default, the release notes go into a **_ReleaseNotes_** folder inside of the **_Documentation_** folder with the **_Documentation_** folder at the root of the repository.
      Production release notes path: **_./Documentation/ReleaseNotes/ProductionReleases_**.

      Release note file names must follow a particular syntax and are in markdown format so they can be added to the release.

      #### Release Notes File Name Syntax:
      - **Production Release Notes:**
        - **Syntax:** Release-Notes-v#.#.#.md
        - **Example:** Release-Notes-v1.2.3.md

      Changes such as release notes and version updates should be committed to the destination branch (master) in the pull request attached to this issue.
      </details>

      ---
  validations:
    required: true
    render: markdown


# CODE OF CONDUCT
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
