name: 🚧 Project Item
description: Create an issue for the project (Project maintainers only).
title: "🚧"
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the 🚧 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ```[tasklist]
      ### The items to complete to satisfy the Definition of Done.
      - [ ] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    value: |
      ```[tasklist]
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
      - [ ] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
      - [ ] Link the issue to the correct milestone _(if applicable)_.
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of issues that are dependencies of this issue and need to be completed first.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10 
        - #20
    description: |
      A list of issues related to this issue but are not a dependency.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Unit Tests</summary>_**
      
      Reasons for local unit test execution:
      - Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
      - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
      - If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

      💡Warning💡
      If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
      Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
      </details>

      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type              | Label                     |
      |:-------------------------|:--------------------------|
      | Bug Fixes                | `🐛bug`                   |
      | Breaking Changes         | `🧨breaking-changes`      |
      | New Feature              | `✨new-feature`           |
      | CICD Changes             | `♻️cicd`                  |
      | Config Changes           | `⚙️config`                |
      | Performance Improvements | `🏎️performance`           |
      | Code Doc Changes         | `🗒️documentation/code`    |
      | Product Doc Changes      | `📝documentation/product` |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label             |
      |---------------------|-------------------|
      | Low Priority        | `low priority`    |
      | Medium Priority     | `medium priority` |
      | High Priority       | `high priority`   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
