name: 🚧 Feature
description: Add a new feature.
type: "Feature"
projects: ["KinsonDigital/11"]
body:
- type: textarea
  attributes:
    label: Description
    description: A description of the feature.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Full manual testing of the feature has been completed.
      - [ ] All the unit tests have been executed and passed locally after the PR work is complete.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Add a priority label to the issue.
      - [ ] Link the issue to the correct milestone _(if applicable)_.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10 
        - #20
    description: |
      A list of issues related to this issue but are not a dependency.
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
