name: 🧪 QA Testing
description: Manual testing of the software with the included results.
title: "QA Testing"
projects: ["KinsonDigital/11"]
type: "QA-Testing"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > 1. The title should be short and descriptive.

- type: textarea
  id: extra-info
  attributes:
    label: Relevant Information
    description: Please enter ANY testing-related information here.

- type: textarea
  id: test-results
  attributes:
    label: QA Testing Results
    description: The QA Testing results such as issue found and any relative information.
    placeholder: |
      Example:
        - #10 
        - #20 
  validations:
    required: false
