name: 🔬 Research Item
description: Create an issue to perform research (Project maintainers only).
type: ["Research"]
projects: ["KinsonDigital/11"]
body:
- type: markdown
  attributes:
    value: "‼️NOTE‼️: Pull requests are not required or used for research issues."

- type: textarea
  attributes:
    label: What To Research
    description: A detailed description of the research to perform.
  validations:
    required: true

- type: textarea
  attributes:
    label: Research Results
    description: This can be notes, links to resources, etc.
    placeholder: "Tip: You can drag and drop files here." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Research complete and issues created _(if needed)_.
      - [ ] If any issues were created, they have been added to the _**Issues Produced**_ section below.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    value: |
      ### Misc. tasks to complete.
      - [ ] Priority label added to this issue.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Issues Produced
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of issues produced from the research.
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
